services:
  - type: web
    name: fgas-app
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install --no-cache-dir reportlab==4.1.0
      python -m pip install -r requirements.txt
      python -c "import sys; print(f'Python path: {sys.path}')"
      python -c "import reportlab; print(f'ReportLab version: {reportlab.__version__}')"
      python -m flask db upgrade
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fgas-db
          property: connectionString

databases:
  - name: fgas-db
    databaseName: fgas
    plan: free
